- .github/workflows/build-docs.yml
- .gitmodules
- README.md
https://akarigroup.github.io/docs/ でドキュメントをホストするようにCIを変更しました。
> Use AkariGroup org to host documents

- source/assembly/setup_soft/main.rst
- source/assembly/setup_soft/setup_ansible.rst
> Fix set up link

- source/intro.rst
> Fix git link

- source/assembly/setup_soft/setup_m5.rst
https://github.com/AkariGroup/akari_software/pull/205
上記に伴って手順修正。
こちらの方がユーザーもやりやすいですね。
> Download m5_sd from cloud

- conf.py
google検索に引っかかるためにsitemapを作る必要があるのですが、この変更をしないと正しいパスが生成されていなかったので修正です。
> Fix sitemap path

- source/assembly/assembly_hard/part_list.rst
> Fix magnet link

- source/dev/custom_object_detection/annotation.rst
Closes #102 
labelImgをgitからセットアップする方式に変更。
試してみてください。
> Fix label img set up procedure

- source/assembly/assembly_hard/assembly_body.rst
- source/assembly/assembly_hard/part_list.rst
ロボットケーブル100mmはディスコン確定なので180mmに変更します。
> Change robot cable

- source/assembly/setup_soft/install_ubuntu.rst
> Fix set up

- source/tutorial/app_repositories.rst
> Add motion server

- source/tutorial/app_repositories.rst
> Add chatgpt_bot sample

- source/tutorial/app_repositories.rst
動画追加漏れがありました。追加します。
マイクとスピーカーがついていない旨追記します。
> Add videos

- source/tutorial/app_repositories.rst
> Add tracking annotator

- source/spec/hard_spec.rst
> Update 3D model

- source/tutorial/app_repositories.rst
> Add joystick controller

- source/ros2/example.rst
画像のリンクを修正。
buildして確認したと思ったのですが…すいません。
> Fix image link

- source/troubleshoot/fix_m5.rst
> Fix M5 trouble shoot

- source/tutorial/app_repositories.rst
akari_tracking_paletteを追加。
動画を足したいけどまだ撮れてない…。
> Add tracking palette

- source/assembly/assembly_hard/part_list.rst
> ADd env4 support

- source/dev/custom_object_detection/training_local.rst
venvでyolov7の学習をさせた場合に起こる可能性のあるエラーへの対処
> Fix yolo train error on venv

- source/tutorial/test_detection.rst
https://github.com/AkariGroup/akari_software/pull/232
に合わせて物体認識チュートリアルを修正
> Fix detection tutorial

- source/assembly/raspi/setup_hard.rst
- source/assembly/raspi/setup_soft.rst
> Add raspberry pi 5 support

- source/tutorial/app_repositories.rst
インディアンポーカーのアプリを追加
akari_yolo_inferenceに動画リンク追加
> Add indian poker and video

- source/intro.rst
- source/troubleshoot/fix_m5.rst
- source/update/main.rst
https://github.com/AkariGroup/akari_software/pull/233
の変更に伴い、パスの修正
(ついでにTwitterのリンク追加)
> Update for new m5 repository

- source/tutorial/app_repositories.rst
> Add good sign counter

- source/tutorial/app_repositories.rst
> Add starry sky

- source/dev/main.rst
- source/dev/remote_api/main.rst
Merge https://github.com/AkariGroup/akari_software/pull/238 first
愛工大のリクエストに沿って、AKARIを外部PCから動かすチュートリアルを作成しました。
> Add remote api tutorial

- source/tutorial/app_repositories.rst
> Add AIT app

- source/tutorial/app_repositories.rst
akari_tracking_captioningとlocal_vlm_serverを追加しました。
> Add tracking captioning app
